name: pr-ci
on: { pull_request: {} }
permissions: { contents: read }
jobs:
  pr-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - run: ruff check .
      - run: mypy .
      - run: pytest --cov=app --cov-report=xml
      - run: bandit -q -r app || true
      - run: pip-audit -r requirements.txt || true
