name: release
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
  id-token: write
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/healthapp-backend
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{ github.actor }}, password: ${{ secrets.GITHUB_TOKEN }} }
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          provenance: false
      - uses: anchore/sbom-action@v0
        with: { image: ${{ env.IMAGE_NAME }}:latest, artifact-name: sbom-spdx.json }
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - uses: sigstore/cosign-installer@v3.8.1
      - name: Sign (keyless)
        env: { COSIGN_EXPERIMENTAL: "1" }
        run: |
          cosign sign --yes ${{ env.IMAGE_NAME }}:latest
          cosign sign --yes ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
